name: modeling
channels:
  - conda-forge
dependencies:
  - joblib=1.0.1
  - jupyterlab=3.2.9
  - matplotlib=3.3.4
  - numpy=1.21.4
  - opencv=4.5.3
  - openjdk=11.0.9.1
  - pandas=1.2.4
  - pillow=8.4.0
  - python=3.9.7
  - ruptures=1.1.3
  - scikit-image
  - scipy=1.7.3
  - seaborn=0.11.0
